/**
 * Seed content: Databases.
 * Contains the prerequisite chain from the product spec:
 *   Normalization ← Duplication, Functional Dependency ← Primary Key ← Row, Column ← Table ← Database
 */
import { Concept, Question, Subject, Topic } from '../domain/types';
import { APP, C, card, E, KI, MC, SA, T } from './helpers';

export const DB_SUBJECT: Subject = {
  id: 's-db',
  name: 'Databases',
  description: 'How structured data is stored, organized, and kept trustworthy.',
  color: '#4C6FE8',
  icon: 'database',
  createdAt: 0,
  updatedAt: 0,
};

export const DB_TOPICS: Topic[] = [
  { id: 't-db-foundations', subjectId: 's-db', name: 'Foundations', description: 'The basic objects every database is built from.', order: 1, createdAt: 0, updatedAt: 0 },
  { id: 't-db-design', subjectId: 's-db', name: 'Design & Normalization', description: 'Keys, dependencies, and designing tables that stay correct.', order: 2, createdAt: 0, updatedAt: 0 },
  { id: 't-db-operations', subjectId: 's-db', name: 'Working With Data', description: 'Finding data fast and combining tables.', order: 3, createdAt: 0, updatedAt: 0 },
];

export const DB_CONCEPTS: Concept[] = [
  C({
    id: 'c-db-database',
    subjectId: 's-db',
    topicId: 't-db-foundations',
    name: 'Database',
    aliases: ['db'],
    intro: 'A database is an organized collection of data that a computer can search, update, and keep consistent.',
    why: 'Without organization, finding one fact among millions means reading everything. Databases exist so that the right piece of data can be found in a fraction of a second, and so two people can update data at the same time without destroying each other’s work.',
    explanations: [
      E('analogy', 'eli5', 'Think of a [[library]]. The books are the data. The catalog, the shelves, and the labeling rules are what make it a *library* instead of a pile of books. A database is the whole library: the data plus the system that keeps it organized.'),
      E('simplified', 'eli5', 'A database is a place where a computer keeps information in an organized way, so it can find and change any piece quickly without breaking the rest.'),
      E('definition', 'what', 'A database is an organized, structured collection of data managed by software (a DBMS) that supports storing, querying, updating, and enforcing consistency.'),
      E('example', 'simple-example', 'A contacts app on your phone uses a database: each contact’s name and number is stored once, and searching “Ma” instantly finds “Maria” — even with thousands of contacts.'),
      E('steps', 'how-it-works', 'How a database answers a request: 1) Your program sends a query (a structured question). 2) The database software looks at which [[table]]s are involved. 3) It uses its internal structure — like an index in a book — to jump straight to relevant rows instead of reading everything. 4) It returns exactly the data you asked for.'),
      E('technical', 'formal', 'Formally: a database is a set of schemas, each containing relations (tables) constrained by integrity rules. A database management system (DBMS) provides transactional access (ACID guarantees: atomicity, consistency, isolation, durability).'),
    ],
    terms: [
      T('data', 'Raw facts — names, numbers, dates — without context.', 'Information a program stores.', '“Maria”, 32, 2026-01-04 are data.', 'Data is the stuff a database stores.'),
      T('query', 'A structured request for data, usually written in a language like SQL.', 'A question you ask the database.', '“Show all contacts named Maria” is a query.', 'Everything you do with a database goes through queries.'),
      T('DBMS', 'Database Management System — the software (like PostgreSQL or SQLite) that manages the database.', 'The program in charge of the data.', 'SQLite inside a phone app is a DBMS.', 'People say “database” but often mean the DBMS.'),
    ],
    examples: {
      simple: 'A single file storing your contacts, with one line per contact.',
      realistic: 'A bank’s database holds millions of accounts and transactions; when you pay online, it updates balances for both sides atomically.',
      counter: 'A folder of random spreadsheets with no naming rules is NOT a database — there is no enforced structure or query system.',
      edge: 'Two apps writing the same file at once will corrupt it; a real database serializes concurrent writes.',
      incorrect: '“A database is any big file with data in it.” Size is not the point — organization and managed access are.',
    },
    keyIdeas: [
      KI('organized', ['organized', 'structured']),
      KI('fast access', ['search', 'find', 'query', 'look up', 'retrieve', 'access']),
      KI('managed by software', ['software', 'dbms', 'system', 'program', 'managed']),
    ],
    prerequisites: [],
    examWeight: 0.9,
    difficultyBase: 0.2,
  }),
  C({
    id: 'c-db-table',
    subjectId: 's-db',
    topicId: 't-db-foundations',
    name: 'Table',
    intro: 'A table is the core container in a relational database: a grid where every row is one item and every column is one kind of fact about it.',
    why: 'The table is the unit of organization inside a database. Every rule about good database design — keys, normalization, relationships — is about how to shape tables.',
    explanations: [
      E('analogy', 'eli5', 'A table is like a [[class register|sign-up sheet]]: each line (row) is one person, and each labeled column — Name, Age, Email — is one kind of fact you wrote down about every person.'),
      E('simplified', 'eli5', 'A table is a grid of data. Each row is one thing (one person, one order). Each column is one type of information (name, price).'),
      E('visual', 'eli5', 'Picture a spreadsheet with strict rules:\n\n  | id | name    | city     |\n  | 1  | Maria   | Madrid   |\n  | 2  | Chen    | Beijing  |\n\nSame number of columns in every row, and every column holds one kind of value.'),
      E('example', 'simple-example', 'A “Students” table: every row is one student; the columns are id, name, and birthdate. Row 1 might be (1, Maria, 2008-04-02).'),
      E('steps', 'how-it-works', 'Inside a table: 1) Columns are defined first, each with a name and a type (text, number, date). 2) Rows are added one at a time, each supplying a value for every column. 3) The database enforces the shape — you can’t add a row with a missing column or a word in a number column (if the rules say so).'),
      E('technical', 'formal', 'In relational theory a table is a relation: a set of tuples over a fixed set of attributed domains. Each row is a tuple; each column is an attribute; each column’s allowed values form its domain.'),
    ],
    terms: [
      T('relational', 'The style of database built from tables that reference each other.', 'Tables that can point at each other.', '“Relational database” = database made of tables.', 'This whole subject is about the relational model.'),
      T('schema', 'The description of a database’s structure: which tables exist and what columns they have.', 'The blueprint of the tables.', '“Users(id, name, email)” is a piece of a schema.', 'Schemas describe tables; tables hold data.'),
      T('record', 'Another word for a row — one item in a table.', 'One entry in the grid.', 'One student’s line in the register.', 'Row = record = tuple; same idea, different words.', 'c-db-row'),
    ],
    examples: {
      simple: 'A “Colors” table: (1, red), (2, green), (3, blue).',
      realistic: 'An “Orders” table with columns order_id, customer_id, product, quantity, ordered_at — one row per order placed.',
      counter: 'A table with a “phone_numbers” column holding two numbers like “555-1234 / 555-9999” is a poorly designed table — that cell holds two values.',
      edge: 'A table with zero rows is still a valid table — the structure (columns) exists even with no data yet.',
      incorrect: 'A table is not “any grid of cells” — a chess board has no typed columns or rows-as-items.',
    },
    keyIdeas: [
      KI('grid of rows and columns', ['grid', 'row', 'rows and columns', 'rows and columns']),
      KI('row = one item', ['one item', 'one thing', 'one person', 'one record', 'one entity', 'each row']),
      KI('column = one kind of fact', ['kind of fact', 'type of information', 'one attribute', 'one property', 'one field', 'one kind']),
    ],
    prerequisites: ['c-db-database'],
    examWeight: 0.9,
    difficultyBase: 0.2,
  }),
  C({
    id: 'c-db-row',
    subjectId: 's-db',
    topicId: 't-db-foundations',
    name: 'Row',
    aliases: ['record', 'tuple'],
    intro: 'A row is one complete item in a table — all the facts about one thing, side by side.',
    why: 'Rows are what your queries actually return and what updates change. Almost every data mistake — duplicates, lost updates, wrong joins — is a mistake about rows.',
    explanations: [
      E('analogy', 'eli5', 'In a [[class register|sign-up sheet]], a row is one person’s entire line: their name, their age, their email — everything together, belonging to that one person.'),
      E('simplified', 'eli5', 'A row is one entry in a table. If the table lists students, one row = one student, with all their info.'),
      E('example', 'simple-example', 'In Students(id, name, city): the row (7, “Amina”, “Cairo”) is one student — read it left to right and you know everything the table knows about student 7.'),
      E('steps', 'how-it-works', 'When you insert data, you insert a row: you supply one value per column, in order. When you update, you pick specific rows and change some of their columns. When you delete, whole rows disappear — never “half a row”.'),
      E('comparison', 'eli5', 'Row vs [[column|Column]]: a row goes across and describes ONE thing completely; a column goes down and collects ONE fact about everything. Mixing these up makes people talk nonsense about tables, so keep the compass: rows across, columns down.'),
    ],
    terms: [
      T('tuple', 'The formal word for a row in relational theory.', 'The theory word for row.', '(7, “Amina”, “Cairo”) is a tuple.', 'Textbooks and exams often say tuple.'),
    ],
    examples: {
      simple: '(3, “Chen”, “Beijing”) — one row of the Students table.',
      realistic: 'In a hospital database, one row in the Appointments table is one booked visit: patient id, doctor id, time, room.',
      counter: 'A row is NOT a column of the table, and not a heading — it is one full data line.',
      edge: 'A row with a NULL in one column still counts as a row — the item exists, one fact about it is just missing.',
      incorrect: '“Rows hold one fact each.” No — rows hold one *item* each, with several facts (columns) inside.',
    },
    keyIdeas: [
      KI('one item per row', ['one item', 'one thing', 'one person', 'one student', 'one order', 'one record', 'one entity', 'single item']),
      KI('all facts together', ['all', 'complete', 'entire', 'everything', 'side by side', 'whole']),
    ],
    prerequisites: ['c-db-table'],
    examWeight: 0.7,
    difficultyBase: 0.15,
  }),
  C({
    id: 'c-db-column',
    subjectId: 's-db',
    topicId: 't-db-foundations',
    name: 'Column',
    aliases: ['field', 'attribute'],
    intro: 'A column is one kind of fact that a table records about every row — with one name and one data type.',
    why: 'Columns define what a table is *about*. Every design decision — keys, dependencies, normalization — is really a decision about what belongs in a column and what doesn’t.',
    explanations: [
      E('analogy', 'eli5', 'On the [[class register|sign-up sheet]], the “Age” column is the column: it collects exactly one kind of fact — an age — from every single person on the sheet.'),
      E('simplified', 'eli5', 'A column is one labeled slot that every row fills in. Name column, age column, email column — each holds one type of information.'),
      E('example', 'simple-example', 'In Students(id, name, city), the column “city” holds a city name for every student. If Chen moves to Shanghai, you update one cell — Chen’s city column.'),
      E('comparison', 'eli5', 'Column vs [[row|Row]]: a column goes down the table and answers ONE question (what city?) for everyone. A row goes across and answers ALL questions for one person. Columns give facts a type; rows give facts a home.'),
      E('steps', 'how-it-works', 'A column is defined by: 1) a unique name within the table, 2) a data type (integer, text, date…), 3) optional rules — NOT NULL, default values. The database then refuses values that break those rules.'),
    ],
    terms: [
      T('attribute', 'The formal word for a column in relational theory.', 'The theory word for column.', '“city” is an attribute of Students.', 'Exams often use attribute for column.'),
      T('data type', 'The kind of value a column accepts: number, text, date, boolean.', 'What shape of value fits the column.', 'An age column with type INTEGER rejects “twenty”.', 'Types are what make columns disciplined.'),
    ],
    examples: {
      simple: 'The “price” column of a Products table: every row has exactly one price.',
      realistic: 'A users table columns: id (number), email (text, unique), created_at (timestamp).',
      counter: 'A “details” column that sometimes holds an address, sometimes a phone number, is a broken column — one column must mean one kind of fact.',
      edge: 'A column can be empty (NULL) for some rows — the column exists regardless.',
      incorrect: '“A column is a list of rows.” A column is a list of *values*, one per row — the row is the item, not the column’s content.',
    },
    keyIdeas: [
      KI('one kind of fact', ['kind of fact', 'type of information', 'one type', 'one kind of', 'single type', 'one attribute']),
      KI('same meaning for every row', ['every row', 'each row', 'all rows', 'for everyone']),
      KI('name and type', ['name', 'type', 'labeled']),
    ],
    prerequisites: ['c-db-table'],
    examWeight: 0.7,
    difficultyBase: 0.15,
  }),
  C({
    id: 'c-db-primary-key',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Primary Key',
    aliases: ['PK'],
    intro: 'A primary key is the column (or set of columns) whose value uniquely identifies each row in a table — no duplicates, no missing values.',
    why: 'Without primary keys you cannot reliably point at a row. Updates would hit the wrong person, two “Maria Garcías” would be indistinguishable, and other tables could never reference yours. The primary key is the anchor of every relationship in a relational database.',
    explanations: [
      E('analogy', 'eli5', 'A primary key is like a [[national ID number|ID number]]: many people can share a name, but each person has exactly one ID number, and no two people share it. To point at one specific person, you use the number — never the name.'),
      E('simplified', 'eli5', 'A primary key is the column that gives every row its own identity. Each value appears once, and it can never be blank.'),
      E('example', 'simple-example', 'Students(id, name): id is the primary key. Maria is 1, Chen is 2, Amina is 3. A second student named Maria gets id 4 — same name, different id, still a different person.'),
      E('steps', 'how-it-works', 'Rules the database enforces for a primary key: 1) UNIQUE — no two rows may share the value. 2) NOT NULL — every row must have one. 3) STABLE in practice — you never reuse or change keys for a different thing. When you try to insert a duplicate, the database rejects the whole insert.'),
      E('comparison', 'eli5', 'Primary key vs [[foreign key|Foreign Key]]: the primary key names rows *inside its own table* (“who am I?”). A foreign key in another table *points* to that primary key (“who do I refer to?”). One identifies; the other references.'),
      E('technical', 'formal', 'Formally: a primary key is a minimal set of attributes whose values are unique over all tuples and never NULL. It is a candidate key chosen by the designer; every table has exactly one primary key (possibly composite).'),
    ],
    terms: [
      T('unique', 'No two rows share the same value in that column.', 'Every value different.', 'Only one row can have id = 7.', 'Uniqueness is what makes the key able to identify a row.'),
      T('composite key', 'A primary key made of two or more columns combined.', 'A key made of several columns stuck together.', 'In Enrollments, (student_id, course_id) together identify one enrollment.', 'Some keys only work as a combination.'),
      T('surrogate key', 'An artificial key (like an auto-number) with no meaning in the real world.', 'A made-up number used as the key.', 'id = 1042 means nothing except “row 1042”.', 'Surrogate keys are stable even when real-world facts change.'),
    ],
    examples: {
      simple: 'Colors(id, name) — id 1, 2, 3. Inserting another row with id 2 fails.',
      realistic: 'In a bank, accounts table has account_number as PK; transactions reference it. One wrong digit = wrong account, so uniqueness is non-negotiable.',
      counter: 'Using “full_name” as a primary key breaks the moment two people share a name — names are not unique.',
      edge: 'A composite key like (student_id, course_id) is fine as a PK: each value alone repeats, but the *pair* never does.',
      incorrect: 'A row with primary key NULL is impossible — the database rejects it. “The key can be blank for unknown rows” is wrong.',
    },
    keyIdeas: [
      KI('uniquely identifies each row', ['unique', 'identify', 'distinguishes', 'no two', 'one row']),
      KI('never null', ['never null', 'not null', 'cannot be blank', 'no missing', 'not blank', 'always has a value']),
      KI('one per table', ['one primary key', 'exactly one', 'single key per table', 'each table has one']),
    ],
    prerequisites: ['c-db-table', 'c-db-row', 'c-db-column'],
    misconceptions: [
      {
        label: 'A primary key can contain NULL',
        wrongIdea: 'A primary key column can be left empty (NULL) for rows where the value is unknown.',
        whyPlausible: 'Other columns can be NULL, so it feels consistent that “unknown” could also mean empty here.',
        whereItBreaks: 'A NULL cannot identify anything — “the row whose key is unknown” could match zero rows or many rows. Identification requires a definite value.',
        correction: 'A primary key is always NOT NULL. If the value is unknown, the row cannot exist yet.',
        contrast: {
          wrong: 'INSERT INTO students (id, name) VALUES (NULL, ’Ana’) — “we’ll fill the id in later.”',
          correct: 'The database rejects a NULL primary key immediately; every row needs a real key from the start.',
        },
        targetedExample: 'Try inserting (NULL, "Ana") into a table with id as PRIMARY KEY — the insert fails with a constraint violation, every time.',
        detectPatterns: ['key can be null', 'primary key null', 'null primary key', 'key is unknown', 'empty primary key', 'blank primary key'],
        checkQuestionIds: ['q-db-pk-null'],
      },
    ],
    examWeight: 1.0,
    difficultyBase: 0.35,
  }),
  C({
    id: 'c-db-foreign-key',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Foreign Key',
    aliases: ['FK'],
    intro: 'A foreign key is a column in one table whose values must match primary key values in another table — it is how tables point at each other.',
    why: 'Foreign keys are how a relational database connects facts that live in different tables: this order belongs to that customer. They also protect you: you cannot create an order for a customer who does not exist.',
    explanations: [
      E('analogy', 'eli5', 'A foreign key is like writing someone’s [[national ID number|ID number]] on a letter. The letter isn’t the person — but the number points at exactly one person. And if you write a number that belongs to nobody, the post office (the database) refuses the letter.'),
      E('simplified', 'eli5', 'A foreign key is a column that stores another table’s primary key. It says: “my row belongs to that row over there.”'),
      E('example', 'simple-example', 'Students(id, name) and Enrollments(student_id, course). In Enrollments, student_id is a foreign key pointing at Students.id. The row (student_id=7, course="Math") means: student number 7 is enrolled in Math.'),
      E('steps', 'how-it-works', 'What the database enforces: 1) You insert an enrollment with student_id = 99. 2) The database checks: does Students have a row with id 99? 3) No → the insert is rejected (referential integrity). This is why you also can’t delete a student who still has enrollments — the pointing rows would dangle.'),
      E('comparison', 'eli5', 'Foreign key vs [[primary key|Primary Key]]: a primary key identifies rows *in its own* table — it is the target. A foreign key lives in a *different* table and stores the target’s value — it is the pointer. Same value, two different jobs: “I am” vs “I refer to”.'),
    ],
    terms: [
      T('referential integrity', 'The rule that a foreign key must always point at a real row.', 'No pointers to nothing.', 'An order for customer 99 fails if customer 99 doesn’t exist.', 'This rule is what keeps connected tables consistent.'),
      T('referenced table', 'The table the foreign key points to (holds the primary key).', 'The table being pointed at.', 'Enrollments points at Students; Students is the referenced table.', 'Describing keys means knowing which side points where.'),
    ],
    examples: {
      simple: 'Pets(owner_id, name): owner_id is a foreign key to People(id). Every pet has exactly one valid owner.',
      realistic: 'Orders(customer_id) → Customers(id). The database blocks an order for a deleted customer — sales data stays honest.',
      counter: 'A foreign key is not an index and not a key *for its own table* — it does not identify rows of the table it lives in.',
      edge: 'A foreign key can be NULL — meaning “not linked yet” (an order not yet assigned to a customer). A primary key never can.',
      incorrect: '“A foreign key is just another primary key.” Wrong — different job, different table, NULL allowed.',
    },
    keyIdeas: [
      KI('points to another table', ['another table', 'other table', 'references', 'points', 'refers', 'points to']),
      KI('matches a primary key', ['primary key', 'matches', 'same value', 'must match']),
      KI('protects consistency', ['reject', 'protect', 'integrity', 'prevent', 'invalid', 'cannot create', 'blocks']),
    ],
    prerequisites: ['c-db-primary-key', 'c-db-table'],
    misconceptions: [
      {
        label: 'A foreign key is just another primary key',
        wrongIdea: 'Foreign keys and primary keys are basically the same thing — both “identify” rows.',
        whyPlausible: 'Both are called “keys”, and both often hold the same values (like the same id numbers).',
        whereItBreaks: 'The primary key identifies rows in its own table and must be unique and non-null. The foreign key lives in a different table, repeats freely (many orders share a customer_id), and can be NULL.',
        correction: 'A primary key says “I am row 7”. A foreign key says “I belong to row 7 of that other table”. Identifier vs pointer.',
        contrast: {
          wrong: '“customer_id in Orders is the primary key of Orders.”',
          correct: 'customer_id in Orders is a foreign key referencing Customers.id; Orders’ own primary key is order_id.',
        },
        targetedExample: 'In Orders, customer_id = 5 appears on 40 different rows — proof it is not identifying anything. order_id is unique — that is the primary key.',
        detectPatterns: ['same as primary key', 'another primary key', 'just a primary key', 'kind of primary key', 'foreign key is the primary'],
        checkQuestionIds: ['q-db-fk-vs-pk'],
      },
    ],
    examWeight: 0.9,
    difficultyBase: 0.4,
  }),
  C({
    id: 'c-db-duplication',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Data Duplication',
    aliases: ['redundancy'],
    intro: 'Data duplication means storing the same fact in more than one place — and it is the root cause of the most dangerous database bugs.',
    why: 'If a customer’s address is stored in five rows and they move, four of those rows can end up stale. Duplicated facts drift apart. Everything called “normalization” exists to eliminate the damage duplication causes.',
    explanations: [
      E('analogy', 'eli5', 'Imagine writing your friend’s phone number on five different sticky notes. When your friend changes numbers, you update two notes… and forget three. Now which one is right? Storing one fact in many places means the copies can disagree. [[database normalization|Normalization]] is the discipline of writing things down once.'),
      E('simplified', 'eli5', 'Duplication is when the same information is saved in several places. That’s bad because when the information changes, some copies get updated and others don’t — and then they contradict each other.'),
      E('example', 'simple-example', 'An Orders table stores customer_name and customer_city on every order. The customer moves city. Now 200 old orders still say “Madrid” while new ones say “Lisbon”. The same fact — the customer’s city — exists in 201 places and they disagree.'),
      E('steps', 'how-it-works', 'How duplication corrupts data: 1) The same fact is copied into many rows. 2) The real-world fact changes. 3) Some copies get updated, others don’t (an update that misses rows, a forgotten report, a manual edit). 4) The copies now disagree — and nothing in the data tells you which copy is true. This disagreement has a name: an update anomaly.'),
      E('comparison', 'eli5', 'Duplication vs [[data redundancy|deliberate redundancy]]: copying a fact by accident is a bug. Deliberately copying *derived* data for speed (like a cache) is a design choice — but it must be rebuildable from the original.'),
    ],
    terms: [
      T('update anomaly', 'When changing a fact in one row leaves contradictory copies in other rows.', 'A change that leaves copies disagreeing.', 'Change the city on one order; 199 others still show the old city.', 'Anomalies are the concrete damage duplication causes.'),
      T('insert anomaly', 'When you cannot record a fact because it only fits inside a row you have no reason to create yet.', 'Can’t add a fact without inventing a whole row.', 'A new customer with zero orders can’t be stored in an orders-only table.', 'The second way duplication hurts.'),
    ],
    examples: {
      simple: 'Writing the product price on every order line *and* in the products table — the two prices can drift apart.',
      realistic: 'A school stores teacher name and room on every course row. Teacher moves rooms → 30 course rows must all be updated; miss one and the timetable lies.',
      counter: 'Storing the *price at time of purchase* on each order is NOT harmful duplication — it’s a different fact (historical price), not a copy of the current price.',
      edge: 'Two rows that happen to contain equal values are not necessarily duplication — duplication is about the same *fact*, not equal bytes.',
      incorrect: '“Duplication just wastes a little disk space.” The space is trivial; the contradictory copies are the disaster.',
    },
    keyIdeas: [
      KI('same fact stored multiple times', ['same fact', 'more than one place', 'multiple places', 'several places', 'copies', 'stored twice', 'repeated']),
      KI('copies drift apart', ['disagree', 'contradict', 'inconsistent', 'out of date', 'stale', 'drift', 'different values', 'out of sync']),
      KI('update anomalies', ['anomaly', 'anomalies', 'update problem', 'forgotten copies']),
    ],
    prerequisites: ['c-db-table', 'c-db-row', 'c-db-column'],
    examWeight: 0.8,
    difficultyBase: 0.35,
  }),
  C({
    id: 'c-db-functional-dependency',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Functional Dependency',
    aliases: ['FD'],
    intro: 'A functional dependency A → B means: whenever two rows agree on A, they must agree on B. The value of A determines the value of B.',
    why: 'Functional dependencies are the microscope of database design. They expose which facts depend on which — and that is exactly the information normalization uses to decide what belongs in a table and what must be split out.',
    explanations: [
      E('analogy', 'eli5', 'Think of a [[national ID number|student ID]]. Student ID → birthdate means: if you know the ID, the birthdate is settled — every record carrying that ID shows the same birthdate. Two rows with the same ID but different birthdates is a contradiction, not a coincidence.'),
      E('simplified', 'eli5', '“A determines B” means: A is enough to know B. If I tell you the student’s ID, you can look up their city — you never need more information. So ID → city.'),
      E('example', 'simple-example', 'In a table of enrollments with columns (student_id, student_name, course): student_id → student_name. Every row where student_id is 7 must show the same name. If one row says (7, “Maria”) and another says (7, “Maria Gomez”) — the dependency is broken and the data is lying.'),
      E('steps', 'how-it-works', 'To check whether A → B holds: 1) Find all rows with the same value of A. 2) Compare their B values. 3) Same B everywhere → the dependency holds (for this data). 4) Any disagreement → A does not determine B. Determining *which* dependencies should hold is a design decision about the real world, not something the data alone can tell you.'),
      E('worked', 'how-it-works', 'Worked check. Table:\n  (course_id, course_name, teacher)\n  (101, Math, Mr. Lee)\n  (101, Math, Mr. Lee)\n  (102, Art, Ms. Kim)\nDoes course_id → course_name? Group by course_id: rows with 101 all say “Math”, rows with 102 all say “Art”. Yes — holds. Does teacher → course_name? Mr. Lee always teaches Math here, so it *happens* to hold in this data — but a teacher can teach two courses, so as a rule about the world it should NOT be assumed. Data suggests; design decides.'),
      E('technical', 'formal', 'Formally, given a relation R, a functional dependency X → Y over R is a constraint: for all tuples t1, t2 ∈ R, if t1[X] = t2[X] then t1[Y] = t2[Y]. X is the determinant set, Y the dependent set. FDs are used to compute normal forms (2NF removes partial dependencies, 3NF removes transitive dependencies).'),
    ],
    terms: [
      T('determines', 'In FD language: knowing A is enough to fix B’s value.', 'A settles B.', 'ID determines birthdate.', '“Determines” is the heart of the definition — and it does NOT mean causes.', 'c-db-functional-dependency'),
      T('determinant', 'The left side of an FD — the thing you know.', 'The left-hand side.', 'In student_id → city, student_id is the determinant.', 'Naming the sides makes FD rules readable.'),
      T('dependent', 'The right side of an FD — the thing that gets settled.', 'The right-hand side.', 'In student_id → city, city is the dependent attribute.', 'The dependent attribute is what normalization moves to its own table.'),
    ],
    examples: {
      simple: 'student_id → student_name: one ID, always one name.',
      realistic: 'In Orders(order_id, customer_id, customer_city): order_id → customer_id, and customer_id → customer_city — so customer_city hangs off order_id only *through* customer_id (a transitive dependency).',
      counter: 'course_name → teacher does not hold in general: “Math” could be taught by different teachers in different years. Equal course names, different teachers — dependency broken.',
      edge: 'A → A always holds (trivial dependency). Also, if A is unique (like a primary key), then A → anything in the row holds — that is exactly why keys matter.',
      incorrect: '“student_id → city means the ID caused the city.” No. Determination is about values coinciding, not causation — the ID doesn’t cause anything.',
    },
    keyIdeas: [
      KI('A determines B', ['determines', 'determine', 'determined by', 'fixes', 'settles', 'decides']),
      KI('same A ⇒ same B', ['same', 'agree', 'must match', 'always the same', 'identical', 'whenever']),
      KI('about values, not causation', ['not cause', 'not causation', 'not about causing', 'values not causes', 'not causal', 'coincide', 'not cause and effect', "doesn't cause", 'does not cause', 'is not caused']),
    ],
    prerequisites: ['c-db-column', 'c-db-row', 'c-db-primary-key'],
    misconceptions: [
      {
        label: 'A → B means A causes B',
        wrongIdea: 'A functional dependency means the determinant causes or influences the dependent attribute.',
        whyPlausible: 'The word “determines” sounds causal, and in real life “X determines Y” often does mean X shapes Y.',
        whereItBreaks: 'An ID number does not cause a birthdate. FDs are constraints about which values may appear together — a bookkeeping rule about consistency, not a claim about cause and effect.',
        correction: 'A → B only means: rows agreeing on A must agree on B. It is about value consistency, never causation.',
        contrast: {
          wrong: '“student_id → birthdate because the ID influences when you were born.”',
          correct: 'student_id → birthdate because each ID belongs to one student, who has one birthdate — a labeling fact, not a causal one.',
        },
        targetedExample: 'Barcode → product name: the barcode does not cause the product’s name. Rename the product and the barcode stays — but every row carrying that barcode must show the new name. Consistency, not causation.',
        detectPatterns: ['causes', 'causes b', 'influences', 'cause and effect', 'leads to b', 'a causes'],
        checkQuestionIds: ['q-db-fd-cause'],
      },
    ],
    examWeight: 1.0,
    difficultyBase: 0.55,
  }),
  C({
    id: 'c-db-normalization',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Database Normalization',
    aliases: ['normalization', 'normalisation', 'normal forms'],
    intro: 'Normalization is the process of restructuring tables so that every fact is stored exactly once — using functional dependencies to decide what belongs together and what must be split apart.',
    why: 'Normalization is the cure for [[data duplication|duplication]]. When every fact lives in one place, updates cannot leave contradictory copies behind, inserts cannot get stuck, and deletes cannot erase facts you wanted to keep. It is the core discipline of database design.',
    explanations: [
      E('analogy', 'eli5', 'Think of a [[shared kitchen]]. If every cook keeps their own private copy of the shopping list, lists drift apart — one says “no more rice”, another still buys rice. Normalization is the house rule: ONE list on the fridge. Everyone reads and updates the same list, so it can never disagree with itself.'),
      E('simplified', 'eli5', 'Normalization means organizing tables so each piece of information is stored in exactly one place. You find which facts depend on which (functional dependencies), and split tables until no fact is repeated.'),
      E('example', 'simple-example', 'Bad: Orders(order_id, customer_name, customer_city). The customer’s name is copied onto every order. Normalized: Customers(id, name, city) + Orders(order_id, customer_id). The name lives once; orders just point at it.'),
      E('steps', 'how-it-works', 'How normalization actually proceeds: 1) Identify the functional dependencies — which columns determine which. 2) Give every entity its own table, with its own primary key. 3) Move each non-key fact next to the key it depends on. 4) Cut every fact that depends on only PART of a composite key (2NF) or on some OTHER non-key column (3NF) into its own table. 5) Check the anomalies again: nothing should be stored twice.'),
      E('comparison', 'eli5', 'Denormalized vs normalized: a denormalized table is fast to read at a glance but dangerous to change — copies drift. A normalized set of tables is safe to change — each fact has one home — but you recombine them with joins when reading. Normalization trades some read convenience for correctness.'),
      E('technical', 'formal', 'Formally, normalization produces relations in normal forms: 1NF (atomic values), 2NF (no partial dependency on a composite key), 3NF (no transitive dependency), each defined by which functional dependencies are allowed to remain. BCNF tightens 3NF so every determinant is a candidate key.'),
      E('scenario', 'realistic', 'A school stores (student_id, student_name, course_id, course_name, teacher). The student moves house — but there is no address here to fix. Then a teacher is renamed: you must update every enrollment row for their courses, and if you miss one, two “truths” exist. Normalized: Students, Courses, Enrollments — rename a teacher in ONE row, everywhere reflects it.'),
    ],
    terms: [
      T('normal form', 'A named level of table organization (1NF, 2NF, 3NF…) defined by which dependencies remain.', 'A checklist level for table design.', '“This table is in 3NF.”', 'Normalization proceeds through the normal forms.', 'c-db-normalization'),
      T('anomaly', 'A way duplicated data breaks: update, insert, or delete anomaly.', 'How bad tables break when changed.', 'Delete the last order of a customer and the customer vanishes too.', 'Anomalies are the symptoms normalization eliminates.'),
      T('decomposition', 'Splitting one table into several, each carrying one kind of fact.', 'Cutting a table into honest pieces.', 'Orders → Customers + Orders.', 'Decomposition is the physical act of normalizing.'),
    ],
    examples: {
      simple: '(order_id, customer_name) → (order_id, customer_id) + (customer_id, customer_name): the name now lives once.',
      realistic: 'A hospital table (patient, ward, ward_phone, doctor, doctor_phone) normalizes into Patients, Wards, Doctors — one phone number each, updated in one place.',
      counter: 'A single-table Excel export is usually NOT normalized, even if it looks tidy — tidiness of layout is not the point; one-fact-one-place is.',
      edge: 'Over-normalization has costs: splitting a rarely-changed fact (like a country’s continent) can add joins for no real benefit. Pragmatic designers sometimes denormalize deliberately — with rules to keep copies in sync.',
      incorrect: 'A normalized database is not automatically faster for every query — it is *safer to change*. Believing “normalized = always faster” confuses correctness with speed.',
    },
    keyIdeas: [
      KI('each fact stored once', ['once', 'one place', 'exactly once', 'single place', 'no duplication', 'not duplicated', 'avoid duplicat', 'eliminates duplicat', 'reduces duplicat', 'one copy']),
      KI('uses functional dependencies', ['functional dependency', 'functional dependencies', 'dependencies', 'depends']),
      KI('eliminates anomalies', ['anomal', 'update problems', 'inconsistenc', 'contradict']),
      KI('split into well-structured tables', ['split', 'separate tables', 'decompos', 'own table', 'restructur', 'reorganiz']),
    ],
    prerequisites: ['c-db-duplication', 'c-db-functional-dependency', 'c-db-primary-key'],
    misconceptions: [
      {
        label: 'Normalization always makes queries faster',
        wrongIdea: 'A normalized database is always faster than a non-normalized one.',
        whyPlausible: 'Normalization is presented as “good design”, and good things sound like they should also be fast. Removing duplication also shrinks tables, which sounds like speed.',
        whereItBreaks: 'Normalization splits data across tables, so reading it back usually requires joins — which cost time. Denormalized reads can be faster; that is why data warehouses deliberately denormalize.',
        correction: 'Normalization optimizes for correctness and maintainability — one fact, one place. Speed is a separate concern, sometimes even fighting normalization.',
        contrast: {
          wrong: '“Normalize the reporting table so reports run faster.”',
          correct: '“Normalize to keep the data consistent; for heavy read-only reporting, denormalized copies are often faster.”',
        },
        targetedExample: 'A weekly sales report reads customer name + city + order total. In a normalized schema that is a join across Customers and Orders. A denormalized reporting table with those columns pre-joined answers the same report faster — which is exactly why warehouses denormalize.',
        detectPatterns: ['always faster', 'makes queries faster', 'faster queries', 'improves speed', 'always speeds', 'guarantees faster', 'makes it fast', 'improves performance'],
        checkQuestionIds: ['q-db-norm-speed'],
      },
    ],
    examWeight: 1.0,
    difficultyBase: 0.6,
  }),
  C({
    id: 'c-db-1nf',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'First Normal Form (1NF)',
    intro: 'A table is in First Normal Form when every cell holds a single atomic value — no lists, no nested tables, one fact per cell.',
    why: '1NF is the entry condition for the relational model: if cells can hold lists, you cannot index, compare, or enforce rules on the values inside. Everything above 1NF assumes it.',
    explanations: [
      E('analogy', 'eli5', 'A [[class register|sign-up sheet]] has one box per field. Writing “Math, Art, Gym” in the “Course” box breaks the sheet — you cannot sort by course or count enrollments. 1NF is the rule: one box, one value.'),
      E('simplified', 'eli5', '1NF means: every cell contains exactly one value. Not a list, not a comma-separated bunch — one thing.'),
      E('example', 'simple-example', 'Not 1NF: Students(id, name, courses) with courses = “Math, Art”. In 1NF: Students(id, name) + Enrollments(student_id, course) — one course per row.'),
      E('steps', 'how-it-works', 'To reach 1NF: 1) Find cells holding multiple values. 2) Move the repeating value into its own table. 3) Link it back with a foreign key. 4) Result: every cell atomic.'),
    ],
    terms: [
      T('atomic value', 'A value that cannot be meaningfully split further for the purposes of the table.', 'One single, unsplittable value.', '“Math” is atomic; “Math, Art” is not.', 'Atomicity is the entire content of 1NF.'),
    ],
    examples: {
      simple: '(1, "Maria", "Math") and (1, "Maria", "Art") — two rows instead of one row with a list.',
      realistic: 'A tags column holding "red,summer,sale" fails 1NF; a ProductTags table with one tag per row passes.',
      counter: 'A full name in one cell is usually acceptable 1NF — unless your queries treat first/last name separately; then split it.',
      edge: 'A fixed composite like a point (x, y) can be atomic if you never query x alone — atomicity is relative to what you need to access.',
      incorrect: '“1NF means no repeated column names like phone1, phone2.” That smell is real, but the definition is about cell contents — phone1/phone2 columns are each atomic; the design is just inflexible.',
    },
    keyIdeas: [
      KI('one value per cell', ['one value', 'atomic', 'single value', 'indivisible', 'one thing per cell', 'no lists']),
      KI('no repeating groups', ['repeating group', 'repeats', 'list', 'comma']),
    ],
    prerequisites: ['c-db-normalization'],
    examWeight: 0.7,
    difficultyBase: 0.35,
  }),
  C({
    id: 'c-db-2nf',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Second Normal Form (2NF)',
    intro: 'A table is in 2NF when it is in 1NF and every non-key column depends on the WHOLE primary key — not just part of it.',
    why: 'Partial dependencies (facts depending on half a composite key) recreate duplication: the same fact appears on every row that shares that half. 2NF removes them.',
    explanations: [
      E('analogy', 'eli5', 'A [[group project]] sign-up sheet lists (student, project, student’s major). The major depends only on the student — not on the project. Copying the major onto every project line repeats one fact many times. 2NF says: student facts live on the student sheet, project membership lives on the membership sheet.'),
      E('simplified', 'eli5', '2NF asks: does every column depend on the entire key? If a column depends on only part of the key, move it to its own table.'),
      E('example', 'simple-example', 'Enrollments(student_id, course_id, grade, course_name): the key is (student_id, course_id). grade depends on both — which student, which course. course_name depends only on course_id — partial! Move it: Courses(course_id, course_name).'),
      E('steps', 'how-it-works', 'To reach 2NF: 1) Confirm 1NF. 2) For each non-key column ask: does it need the WHOLE key to be determined? 3) Columns depending on only part of the key move to a new table keyed by that part. 4) Original table keeps only whole-key facts.'),
    ],
    terms: [
      T('partial dependency', 'A non-key column that depends on only part of a composite key.', 'Depending on half the key.', 'course_name depends only on course_id (half of the key).', 'Partial dependencies are exactly what 2NF forbids.'),
    ],
    examples: {
      simple: 'Enrollments(student_id, course_id, grade, course_name) → split course_name into Courses.',
      realistic: 'OrderLines(order_id, product_id, quantity, product_price): price depends only on product → move to Products; keep the historical price if needed as a distinct fact.',
      counter: 'If the primary key is a single column, the table is automatically in 2NF — there is no “part” of a one-column key to depend on.',
      edge: 'grade in Enrollments depends on BOTH student and course — that is a full dependency; it stays.',
      incorrect: '“2NF removes facts unrelated to the key.” That is 3NF’s job — 2NF is strictly about parts of composite keys.',
    },
    keyIdeas: [
      KI('in 1NF first', ['1nf', 'first normal form']),
      KI('no partial dependency', ['whole key', 'entire key', 'full key', 'partial', 'part of the key', 'complete key']),
      KI('only applies to composite keys', ['composite', 'single column', 'simple key']),
    ],
    prerequisites: ['c-db-1nf', 'c-db-functional-dependency'],
    examWeight: 0.8,
    difficultyBase: 0.55,
  }),
  C({
    id: 'c-db-3nf',
    subjectId: 's-db',
    topicId: 't-db-design',
    name: 'Third Normal Form (3NF)',
    intro: 'A table is in 3NF when it is in 2NF and no non-key column depends on another non-key column — no transitive dependencies.',
    why: 'Transitive dependencies chain facts through non-key columns, so one real-world fact hides inside another column’s shadow — duplicated across rows again. 3NF closes the last common duplication hole.',
    explanations: [
      E('analogy', 'eli5', 'A delivery note lists (package_id, zip_code, city). The city depends on the zip — not on the package. Storing city on every package repeats zip-code knowledge on every line. 3NF: Packages keep the zip; a ZipCodes table owns the city.'),
      E('simplified', 'eli5', '3NF asks: does any column depend on another regular column instead of the key? If yes, move that fact to its own table.'),
      E('example', 'simple-example', 'Employees(emp_id, dept_id, dept_name): emp_id → dept_id, and dept_id → dept_name. So dept_name depends on a non-key column. Split: Departments(dept_id, dept_name); Employees keeps dept_id only.'),
      E('steps', 'how-it-works', 'To reach 3NF: 1) Confirm 2NF. 2) For each non-key column ask: would it be determined even if I only knew another non-key column? 3) Such columns move to a new table keyed by the column they depend on. 4) What remains: key + facts that depend directly on the key.'),
      E('technical', 'formal', '3NF: for every non-trivial FD X → A, either X is a superkey, or A is a prime attribute. Informally: no transitive dependencies of non-key attributes.'),
    ],
    terms: [
      T('transitive dependency', 'A non-key column that depends on another non-key column rather than the key.', 'Fact chained through another column.', 'dept_id → dept_name inside Employees.', 'Transitive dependencies are what 3NF removes.'),
    ],
    examples: {
      simple: 'Employees(emp_id, dept_id, dept_name) → Departments(dept_id, dept_name) + Employees(emp_id, dept_id).',
      realistic: 'Patients(patient_id, ward, ward_phone): ward_phone depends on ward → Wards(ward, phone) and Patients keep ward only.',
      counter: 'A computed column like age derived from birthdate is not a transitive dependency in the dangerous sense — but storing both duplicates a fact; store birthdate, compute age.',
      edge: 'In a table where dept_id IS part of the key, dept_name depending on it is a partial dependency (2NF problem), not a 3NF problem. Same split, different rule number.',
      incorrect: '“3NF means no column may reference another table.” False — foreign keys are fine; 3NF constrains dependencies *within* the table.',
    },
    keyIdeas: [
      KI('in 2NF first', ['2nf', 'second normal form']),
      KI('no transitive dependency', ['transitive', 'non-key column depends', 'depends on another column', 'non-key to non-key']),
      KI('facts depend on the key', ['depend on the key', 'the key', 'key, the whole key', 'nothing but the key']),
    ],
    prerequisites: ['c-db-2nf', 'c-db-functional-dependency'],
    examWeight: 0.8,
    difficultyBase: 0.6,
  }),
  C({
    id: 'c-db-index',
    subjectId: 's-db',
    topicId: 't-db-operations',
    name: 'Index',
    intro: 'An index is a data structure the database keeps beside a table so it can find rows by a column’s value without scanning the whole table.',
    why: 'Without an index, “find the user with email = x” reads every row. With an index, the database jumps almost directly to the match — the difference between milliseconds and minutes on large tables.',
    explanations: [
      E('analogy', 'eli5', 'An index is the [[index|index at the back of a book]]. To find “normalization” you don’t read every page — you jump to the index, see “pages 88–92”, and go straight there. The index is extra structure you maintain so lookups are fast.'),
      E('simplified', 'eli5', 'An index is a lookup helper the database builds automatically. Ask about an indexed column and it finds rows instantly instead of checking every one.'),
      E('example', 'simple-example', 'Users(id, email) with a million rows. Query “WHERE email = ’a@x.com’”: without an index — up to a million checks; with an index on email — a handful of steps (a tree descent).'),
      E('comparison', 'eli5', 'Index vs [[primary key|primary key]]: a primary key is a rule about identity (unique, never null); an index is a performance structure. Most databases automatically build an index behind primary keys — which is why they confuse people.'),
      E('steps', 'how-it-works', 'The trade-off: 1) An index speeds up reads on that column. 2) Every insert/update must also update the index — writes get slightly slower. 3) The index takes storage. So you index the columns you actually search by, not everything.'),
    ],
    terms: [
      T('B-tree', 'The balanced tree structure most indexes use: sorted, so lookups descend level by level.', 'The sorted tree structure indexes use.', 'Like a family tree of sorted values guiding a search.', 'B-trees are why index lookups stay fast as data grows.'),
      T('table scan', 'Reading every row of a table to answer a query — what indexes exist to avoid.', 'Checking every single row.', 'Looking for a word by reading a whole book page by page.', '“Avoiding full table scans” is the point of indexing.'),
    ],
    examples: {
      simple: 'Index on Users.email: logging in by email becomes near-instant.',
      realistic: 'A shop indexes product names for the search box but not the internal notes field nobody searches.',
      counter: 'An index on a column with two distinct values (yes/no) helps little — nearly every row matches anyway.',
      edge: 'Too many indexes slow down inserts — every index must be updated on every write.',
      incorrect: '“Indexes and primary keys are the same thing.” No — one is a speed structure, the other an identity rule; they just often travel together.',
    },
    keyIdeas: [
      KI('speeds up lookups', ['fast', 'speed', 'quick', 'lookup', 'find quickly', 'avoid scanning', 'without scanning']),
      KI('extra structure beside the table', ['structure', 'beside', 'separate', 'extra', 'auxiliary']),
      KI('costs on writes', ['slower writes', 'insert slower', 'trade-off', 'maintenance cost', 'overhead']),
    ],
    prerequisites: ['c-db-table', 'c-db-column'],
    examWeight: 0.7,
    difficultyBase: 0.4,
  }),
  C({
    id: 'c-db-join',
    subjectId: 's-db',
    topicId: 't-db-operations',
    name: 'JOIN',
    intro: 'A JOIN combines rows from two tables by matching values — usually a foreign key against the primary key it points to.',
    why: 'Normalized data lives in separate tables — customers here, orders there. A JOIN is how you ask a question that spans both: “show each order with its customer’s name”. Without joins, normalization would make data unreadable.',
    explanations: [
      E('analogy', 'eli5', 'A JOIN is like matching [[luggage tags]] to passengers. Each suitcase (order) carries a tag with a passenger ID (foreign key). Walk the belts and the passenger list together: for each tag, find the matching passenger, and put the name on the suitcase. That pairing is a join.'),
      E('simplified', 'eli5', 'A JOIN glues two tables together for one query: for each row in one table, find the matching row in the other (where the shared values agree) and show them side by side.'),
      E('example', 'simple-example', 'Orders(order_id, customer_id) and Customers(id, name). JOIN on customer_id = id produces rows like (order_id, customer_id, name) — every order now carries its customer’s name.'),
      E('steps', 'how-it-works', 'How a join runs: 1) Pick the join condition (which columns must match). 2) For each row of the left table, find rows of the right table with matching values (using an index when available). 3) Emit one combined row per match. Variants: INNER keeps only matches; LEFT keeps unmatched left rows with NULLs on the right.'),
      E('comparison', 'eli5', 'JOIN vs merging tables: a join is a *query-time* combination — the two tables still exist separately and stay normalized. Physically merging them into one stored table is the opposite move (denormalization) and reintroduces duplication.'),
    ],
    terms: [
      T('join condition', 'The matching rule for the join — which columns must be equal.', 'Which columns get matched.', 'ON orders.customer_id = customers.id', 'The condition decides which rows pair up.'),
      T('INNER / LEFT JOIN', 'INNER keeps only matching pairs; LEFT also keeps left rows with no match (filling the right side with NULL).', 'Two flavors of join strictness.', 'LEFT JOIN lists customers even if they have zero orders.', 'Choosing the flavor changes which rows survive.'),
    ],
    examples: {
      simple: 'Orders JOIN Customers on customer_id = id: each order gains its customer’s name.',
      realistic: 'A grade report: Enrollments JOIN Students JOIN Courses — three tables, one readable table of (student, course, grade).',
      counter: 'A join with the wrong condition (e.g., matching on name instead of id) can pair the wrong rows — joins trust you to match the right keys.',
      edge: 'A LEFT JOIN keeps customers with zero orders (their order columns are NULL) — exactly how you find “customers who never ordered”.',
      incorrect: '“A JOIN physically merges the tables permanently.” No — it combines them for the duration of one query; the stored tables never change.',
    },
    keyIdeas: [
      KI('combines rows from two tables', ['combine', 'two tables', 'bring together', 'glue', 'pair', 'match rows', 'merge for the query']),
      KI('matches on shared values', ['match', 'matching', 'shared', 'condition', 'equal', 'on']),
      KI('query-time, tables unchanged', ['query', 'temporary', 'not stored', 'tables unchanged', 'does not change', 'for the query']),
    ],
    prerequisites: ['c-db-table', 'c-db-foreign-key', 'c-db-row'],
    misconceptions: [
      {
        label: 'A JOIN physically merges tables',
        wrongIdea: 'Running a JOIN permanently combines the two tables into one stored table.',
        whyPlausible: 'The result *looks* like one merged table, and “join” in everyday speech means sticking things together permanently.',
        whereItBreaks: 'A join is a query over the data, not a change to the data. Run the same join twice — the underlying tables are untouched; the combination is recomputed each time.',
        correction: 'JOIN combines rows at query time. The stored tables stay separate and normalized.',
        contrast: {
          wrong: '“After we joined Orders and Customers, our data now lives in one big table.”',
          correct: 'The joined result existed only for that query; Orders and Customers remain two tables.',
        },
        targetedExample: 'Run `SELECT * FROM orders JOIN customers ON orders.customer_id = customers.id` twice. Then check each table: both still exist, unchanged, with their original row counts.',
        detectPatterns: ['merges permanently', 'physically merges', 'permanently combines', 'combines the tables into one', 'one big table', 'stored as one'],
        checkQuestionIds: ['q-db-join-merge'],
      },
    ],
    examWeight: 0.9,
    difficultyBase: 0.45,
  }),
];

export const DB_QUESTIONS: Question[] = [
  // ---- Database ----
  MC('q-db-database-guided', 'c-db-database', 'What is a database, in one phrase?', ['A big file with numbers in it', 'An organized collection of data a computer can search and keep consistent', 'A programming language', 'A screen for typing data'], { correctIndex: 1, difficultyBase: 0.2, hints: ['Think about what makes it different from a random pile of files.', 'The key words are: organized, searchable, managed.', 'It is organized data managed by software.'] }),
  SA('q-db-database-confirm', 'c-db-database', 'Why do we use a database instead of just keeping files?', 'so specific data can be found quickly and stays consistent', [['organized', 'structured'], ['search', 'find', 'query', 'look up', 'retrieve'], ['consistent', 'correct', 'reliable', 'without breaking']], { difficultyBase: 0.3, hints: ['Imagine finding one contact among 10,000 in a plain text file.', 'Two problems: finding things fast, and keeping them correct when many things change.'] }),
  APP('q-db-database-apply', 'c-db-database', 'A team keeps project data in one shared spreadsheet. Two members open it at once, both edit, and one version silently overwrites the other. Which database property directly addresses this?', 'managed concurrent access — the DBMS keeps writes consistent', [['concurrent', 'at the same time', 'simultaneous'], ['consistency', 'consistent', 'without destroying', 'not overwrite', 'safe']], { difficultyBase: 0.45 }),

  // ---- Table ----
  MC('q-db-table-guided', 'c-db-table', 'In a table, what does one row contain?', ['One kind of fact about everything', 'One complete item, with a value for every column', 'The column names', 'A random piece of data'], { correctIndex: 1, difficultyBase: 0.2, hints: ['Think of a sign-up sheet: what is one line of the sheet?'] }),
  MC('q-db-table-confirm', 'c-db-table', 'A table “Cars” has columns (id, brand, color). Which statement is true?', ['Each row is one car with a brand and a color', 'Each row is a brand', 'The color column holds one car per color', 'Rows and columns are interchangeable'], { correctIndex: 0, difficultyBase: 0.25, hints: ['One row = one item. What is the item here?'] }),
  SA('q-db-table-apply', 'c-db-table', 'You must store members of a club: each has a name, join date, and email. Describe the table you would create.', 'one row per member with columns name, join date, email', [['row', 'one row', 'each row', 'per member'], ['column', 'field'], ['name'], ['email', 'date']], { difficultyBase: 0.4 }),

  // ---- Row ----
  MC('q-db-row-guided', 'c-db-row', 'In Students(id, name, city), the line (7, “Amina”, “Cairo”) is called a…', ['column', 'row — one complete item', 'table', 'schema'], { correctIndex: 1, difficultyBase: 0.15 }),
  MC('q-db-row-col-confuse', 'c-db-row', 'Which is TRUE about rows?', ['A row holds one complete item across all columns', 'A row holds one kind of fact for every item', { text: 'A row is the same thing as a column rotated', conceptId: 'c-db-column' }, 'A row is a heading'], { correctIndex: 0, difficultyBase: 0.25, hints: ['Rows go across; columns go down.'] }),

  // ---- Column ----
  MC('q-db-column-guided', 'c-db-column', 'What does one column contain?', ['One complete item', 'One kind of fact, one value per row', 'All the data of the table', 'The table’s name'], { correctIndex: 1, difficultyBase: 0.15 }),
  MC('q-db-col-row-confuse', 'c-db-column', 'Which is TRUE about the “city” column of a Students table?', ['It collects one city value from every row', 'It lists all facts about one student', { text: 'It is a row for cities', conceptId: 'c-db-row' }, 'It exists only when rows are empty'], { correctIndex: 0, difficultyBase: 0.25 }),

  // ---- Primary Key ----
  MC('q-db-pk-guided', 'c-db-pk', 'What is the job of a primary key?', ['Make the table faster', 'Uniquely identify each row', 'Encrypt the data', 'List the column names'], { correctIndex: 1, difficultyBase: 0.25, hints: ['Many people can share a name. What do you use to point at exactly one?'] }),
  MC('q-db-pk-confirm', 'c-db-primary-key', 'Students uses id as primary key. Someone inserts two rows with id = 7. What happens?', ['Both rows are stored', { text: 'The second insert is rejected — keys must be unique', misconceptionId: 'md_c-db-primary-key_a-primary-key-can-contain-null' }, 'The two rows are merged', 'The id changes automatically'], { correctIndex: 1, difficultyBase: 0.3 }),
  MC('q-db-pk-null', 'c-db-primary-key', 'Which row can legally exist in a table whose primary key is id?', ['(NULL, "Ana")', { text: '(NULL, "Ana") is fine, keys can be unknown', misconceptionId: 'md_c-db-primary-key_a-primary-key-can-contain-null' }, '(7, "Ana")', '("later", "Ana", "extra")'], { correctIndex: 2, difficultyBase: 0.35, targetsMisconception: 'md_c-db-primary-key_a-primary-key-can-contain-null', hints: ['Can a missing value identify anything?', 'If the key is unknown, which row does it point to?', 'Primary keys are never NULL — that rules out every NULL option.'] }),
  MC('q-db-pk-which', 'c-db-primary-key', 'A People table will store name, phone, and email. Which column is the best primary key?', ['name — people have names', 'email — unless two people share an account, which happens', 'phone — people can share phones too', 'id — an auto-generated unique number'], { correctIndex: 3, difficultyBase: 0.4, hints: ['Ask: can this value repeat or go missing for two different people?', 'Real-world attributes can repeat. What never repeats by construction?'] }),
  APP('q-db-pk-apply', 'c-db-primary-key', 'A library catalog accidentally has two book records with the same ISBN, and loans reference “the book with ISBN X”. What problem does this create, and what does it show about keys?', 'a loan cannot tell which record it means; identity must be unique', [['unique', 'two records', 'same isbn', 'duplicate', 'ambiguous'], ['identify', 'which', 'ambiguous', 'cannot tell', 'not unique']], { difficultyBase: 0.5 }),

  // ---- Foreign Key ----
  MC('q-db-fk-guided', 'c-db-foreign-key', 'What does a foreign key do?', ['Identifies rows inside its own table', 'Points to the primary key of another table', 'Sorts the table', 'Encrypts connections'], { correctIndex: 1, difficultyBase: 0.3, hints: ['One is “I am row 7”. Which one says “I belong to row 7 over there”?'] }),
  MC('q-db-fk-vs-pk', 'c-db-foreign-key', 'In Orders(order_id, customer_id), what is customer_id?', ['The primary key of Orders', { text: 'The primary key of Orders, just with another name', misconceptionId: 'md_c-db-foreign-key_a-foreign-key-is-just-another-primary-key' }, 'A foreign key referencing Customers.id — it repeats freely across rows', 'An index'], { correctIndex: 2, difficultyBase: 0.35, targetsMisconception: 'md_c-db-foreign-key_a-foreign-key-is-just-another-primary-key', hints: ['How many orders can belong to the same customer?', 'A key that repeats on 40 rows cannot be identifying rows of Orders.', 'order_id identifies Orders rows; customer_id points elsewhere.'] }),
  APP('q-db-fk-apply', 'c-db-foreign-key', 'A Pets table has owner_id pointing at People(id). Someone tries to insert a pet with owner_id = 99, but no person 99 exists. What should the database do, and why?', 'reject the insert because the foreign key must point at a real row', [['reject', 'refuse', 'block', 'not allow', 'fail'], ['real', 'existing', 'must exist', 'points to', 'referential']], { difficultyBase: 0.45 }),
  MC('q-db-fk-repeat', 'c-db-foreign-key', 'How many rows of Orders can carry customer_id = 5?', ['At most one', 'Exactly as many orders as customer 5 has — the value repeats freely', 'None, values may appear once', 'Two'], { correctIndex: 1, difficultyBase: 0.35 }),

  // ---- Duplication ----
  MC('q-db-dup-guided', 'c-db-duplication', 'What is the real danger of storing the same fact in many rows?', ['It uses more disk space', 'When the fact changes, some copies get updated and others don’t — they contradict each other', 'It makes the table longer to read', 'Databases forbid it'], { correctIndex: 1, difficultyBase: 0.3, hints: ['Space is cheap. What is expensive is when copies disagree.', 'Update one copy… what happens to the rest?'] }),
  MC('q-db-dup-confirm', 'c-db-duplication', 'Orders stores customer_city on every order row. The customer moves. What is the likely outcome?', ['All rows update themselves automatically', 'Some rows show the old city and some the new — an update anomaly', 'The database deletes the customer', 'Nothing, cities never change'], { correctIndex: 1, difficultyBase: 0.3 }),
  APP('q-db-dup-apply', 'c-db-duplication', 'A recipe app stores the author’s name on every recipe. The author changes their display name. Describe the problem and the fix.', 'old copies keep the old name and copies disagree; store the author once and reference by id', [['old', 'stale', 'not all updated', 'disagree', 'some still', 'out of date'], ['store once', 'own table', 'reference', 'by id', 'one place', 'separate table']], { difficultyBase: 0.45 }),

  // ---- Functional Dependency ----
  MC('q-db-fd-guided', 'c-db-functional-dependency', '“student_id → city” means…', ['The student’s ID was caused by their city', 'Whenever two rows have the same student_id, they must have the same city', 'The city column comes before the ID', 'Every student lives in a different city'], { correctIndex: 1, difficultyBase: 0.35, hints: ['It is a rule about rows agreeing, not about causes.', 'Take two rows with the same ID. What must be true?'] }),
  MC('q-db-fd-cause', 'c-db-functional-dependency', 'Does “student_id → birthdate” mean the ID *causes* the birthdate?', ['Yes, that is what determines means', { text: 'Yes — the number influences the birthdate', misconceptionId: 'md_c-db-functional-dependency_a-b-means-a-causes-b' }, 'No — it only means rows sharing the ID must share the birthdate; it is about consistency, not causation', 'No — it means the birthdate is random'], { correctIndex: 2, difficultyBase: 0.4, targetsMisconception: 'md_c-db-functional-dependency_a-b-means-a-causes-b', hints: ['Does a number cause a date of birth?', '“Determines” here means “settles the value”, not “creates the fact”.'] }),
  SA('q-db-fd-confirm', 'c-db-functional-dependency', 'Enrollments has (student_id, course, grade). You find (7, Math, A) and (7, Math, C). What does this tell you if student_id → grade is claimed to hold?', 'the dependency is violated — same student and course must give the same grade', [['violat', 'broken', 'not hold', "doesn't hold", 'inconsist', 'wrong', 'contradict', 'impossible', 'error'], ['same']], { difficultyBase: 0.45 }),
  APP('q-db-fd-apply', 'c-db-functional-dependency', 'In a Courses table you observe: (101, Math, Mr. Lee), (101, Math, Mr. Lee), (102, Art, Ms. Kim). Does course_id → teacher hold in this data? Should you rely on it as a design rule?', 'it holds in this data but not as a rule — a teacher can teach several courses', [['holds', 'true', 'yes'], ['but', 'however', 'should not', 'cannot rely', 'not a rule', 'may change', 'not safe', 'could change', 'not guaranteed']], { difficultyBase: 0.55 }),
  APP('q-db-fd-transfer', 'c-db-functional-dependency', 'New context: a music app. Table Plays(user_id, song_id, times_played, song_title). Rows: (u1, s9, 12, "Yesterday"), (u2, s9, 3, "Yesterday"), (u1, s9, 12, "Yesterday"). Which functional dependency is clearly present, and which is suspicious?', 'song_id → song_title holds; song_id → times_played is suspicious because times differ per user', [['song_id', 'title'], ['user_id', 'times', 'per user', 'differ', 'depends on user']], { difficultyBase: 0.6, isTransfer: true }),

  // ---- Normalization ----
  MC('q-db-norm-guided', 'c-db-normalization', 'What is the core goal of normalization?', ['Make every query as fast as possible', 'Store each fact in exactly one place so updates cannot leave contradictory copies', 'Sort all rows alphabetically', 'Combine all tables into one'], { correctIndex: 1, difficultyBase: 0.35, hints: ['What problem did duplication cause? Normalization is its cure.', 'One fact, one place.'] }),
  MC('q-db-norm-speed', 'c-db-normalization', 'Your team normalized a reporting database, but the weekly report became SLOWER. Is this surprising?', ['Yes — normalization always speeds queries up', { text: 'Yes — normalized databases are guaranteed to be faster', misconceptionId: 'md_c-db-normalization_normalization-always-makes-queries-faster' }, 'No — normalization optimizes correctness; the report now needs joins, so denormalized copies are often faster for read-heavy reports', 'No — but only because the database is old'], { correctIndex: 2, difficultyBase: 0.45, targetsMisconception: 'md_c-db-normalization_normalization-always-makes-queries-faster', hints: ['What did normalization promise to optimize — speed or consistency?', 'Normalization splits tables. What does reading them back together require?', 'Joins cost time. That is why warehouses denormalize for reads.'] }),
  SA('q-db-norm-confirm', 'c-db-normalization', 'In one sentence: why does normalization prevent the “customer moved city” bug?', 'the city is stored once so there is only one copy to update', [['once', 'one place', 'single place', 'one copy', 'only one'], ['update', 'change']], { difficultyBase: 0.4 }),
  APP('q-db-norm-apply', 'c-db-normalization', 'A clinic stores (visit_id, patient_name, patient_birthdate, doctor_name, doctor_room). The hospital renames a ward and every doctor’s room changes. Describe how to normalize this table.', 'split into Patients, Doctors, Visits so each fact lives once and is referenced by id', [['patients', 'patient table', 'patient'], ['doctors', 'doctor table', 'doctor'], ['visits', 'visit table', 'visit'], ['id', 'reference', 'foreign key', 'key']], { difficultyBase: 0.55 }),
  APP('q-db-norm-transfer', 'c-db-normalization', 'Transfer scenario: a music app stores (playlist_id, playlist_name, owner_name, song_id, song_title) — one row per song in a playlist, with playlist and owner info repeated on every row. What are the anomalies, and how do you restructure it?', 'renaming a playlist or owner means updating many rows and copies can disagree; split into Playlists, Owners, Users and PlaylistSongs', [['many rows', 'every row', 'repeated', 'copies', 'disagree', 'anomaly', 'update'], ['split', 'separate', 'own table', 'playlists', 'playlistsongs']], { difficultyBase: 0.65, isTransfer: true }),

  // ---- 1NF ----
  MC('q-db-1nf-guided', 'c-db-1nf', 'Which table is in First Normal Form?', ['Students(id, courses) where courses = "Math, Art"', 'Students(id, course) with one row per course per student', 'Students(id, "Math, Art") is fine if it saves rows', 'Students(courses…) with a column per course'], { correctIndex: 1, difficultyBase: 0.3 }),
  APP('q-db-1nf-apply', 'c-db-1nf', 'A Products table has a column tags containing "red,summer,sale". How do you bring it to 1NF?', 'a ProductTags table with one row per product-tag pair', [['producttags', 'separate table', 'own table', 'one row per tag', 'one tag per row']], { difficultyBase: 0.4 }),

  // ---- 2NF ----
  MC('q-db-2nf-guided', 'c-db-2nf', 'Enrollments(student_id, course_id, grade, course_name) with key (student_id, course_id). Why is course_name a 2NF problem?', ['It depends only on course_id — part of the key', 'It is too long', 'It depends on nothing', 'Grades are subjective'], { correctIndex: 0, difficultyBase: 0.45, hints: ['Which half of the key already settles the course name?'] }),
  APP('q-db-2nf-apply', 'c-db-2nf', 'OrderLines(order_id, product_id, quantity, product_name) with key (order_id, product_id). Identify the partial dependency and the fix.', 'product_name depends only on product_id; move it to a Products table', [['product_name', 'name'], ['product_id', 'product'], ['products', 'own table', 'move', 'separate']], { difficultyBase: 0.5 }),

  // ---- 3NF ----
  MC('q-db-3nf-guided', 'c-db-3nf', 'Employees(emp_id, dept_id, dept_name). Which dependency makes this NOT 3NF?', ['emp_id → dept_id', 'dept_id → dept_name — a non-key column depending on another non-key column', 'emp_id → dept_name', 'dept_name → emp_id'], { correctIndex: 1, difficultyBase: 0.45 }),
  APP('q-db-3nf-apply', 'c-db-3nf', 'Patients(patient_id, ward, ward_phone). What do you split out, and what stays?', 'Wards(ward, phone) is split out; Patients keeps patient_id and ward', [['wards', 'ward table'], ['phone'], ['patients keep', 'stays', 'patient_id']], { difficultyBase: 0.5 }),

  // ---- Index ----
  MC('q-db-index-guided', 'c-db-index', 'What is an index for?', ['Encrypting columns', 'Finding rows by a column’s value without scanning the whole table', 'Numbering rows automatically', 'Linking tables together'], { correctIndex: 1, difficultyBase: 0.3 }),
  MC('q-db-index-cost', 'c-db-index', 'What is the main cost of adding an index?', ['The table gets shorter', 'Every insert and update must also maintain the index', 'Queries lose results', 'Columns become unique'], { correctIndex: 1, difficultyBase: 0.4 }),

  // ---- JOIN ----
  MC('q-db-join-guided', 'c-db-join', 'What does a JOIN do?', ['Physically merges two tables into one stored table', 'Combines rows from two tables for one query by matching values', 'Deletes unmatched rows from both tables', 'Creates an index'], { correctIndex: 1, difficultyBase: 0.3, hints: ['The stored tables never change. What changes is the query result.'] }),
  MC('q-db-join-merge', 'c-db-join', 'After running `orders JOIN customers`, an intern says “our two tables are now one big table”. What is wrong with this?', ['Nothing, joins merge tables permanently', { text: 'Nothing — that is exactly what a join does', misconceptionId: 'md_c-db-join_a-join-physically-merges-tables' }, 'The join only combined rows for that query result; both tables still exist separately and unchanged', 'The tables are merged until the database restarts'], { correctIndex: 2, difficultyBase: 0.4, targetsMisconception: 'md_c-db-join_a-join-physically-merges-tables', hints: ['Run the join twice. Did anything about the stored tables change?', 'A join is a question you ask, not an edit you make.'] }),
  APP('q-db-join-apply', 'c-db-join', 'Customers(id, name) has Maria (id 1). Orders(order_id, customer_id) has three orders with customer_id = 1. Describe the JOIN result on customer_id = id.', 'three combined rows, each pairing one order with Maria’s name', [['three', '3', 'each order'], ['maria', 'name', 'customer']], { difficultyBase: 0.45 }),
  MC('q-db-join-left', 'c-db-join', 'You need “all customers, with their order count, including customers with zero orders”. Which join do you need?', ['INNER JOIN', 'LEFT JOIN — keeps customers without matches (right side NULL)', 'RIGHT JOIN on customers', 'No join, just a table scan'], { correctIndex: 1, difficultyBase: 0.5 }),
];

export const DB_CARDS = [
  card('c-db-database', 'What is a database?', 'An organized collection of data managed by software that supports fast search and consistent updates.'),
  card('c-db-primary-key', 'What rules does a primary key follow?', 'Unique across rows, never NULL, one per table — it identifies each row.'),
  card('c-db-foreign-key', 'What does a foreign key guarantee?', 'Each value matches a primary key in the referenced table (referential integrity).'),
  card('c-db-functional-dependency', 'A → B means…', 'Whenever rows agree on A, they must agree on B. Values, not causes.'),
  card('c-db-normalization', 'What does normalization optimize for?', 'Correctness and maintainability: each fact stored exactly once. Not raw speed.'),
  card('c-db-2nf', '2NF removes…', 'Partial dependencies: non-key columns depending on part of a composite key.'),
  card('c-db-3nf', '3NF removes…', 'Transitive dependencies: non-key columns depending on other non-key columns.'),
  card('c-db-join', 'What is a JOIN?', 'A query-time combination of rows from two tables matched on shared values — stored tables unchanged.'),
];
